apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    command:
      - /bin/sleep
    args:
      - 300s
    imagePullPolicy: Always
    name: nginx
    resources:
      requests:
        memory: 1G
        cpu: 1
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
    volumeMounts:
    - mountPath: /tmp
      name: temp
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
    kubernetes.io/hostname: podman
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  volumes:
  - hostPath:
      path: /tmp/test
      type: DirectoryOrCreate
    name: temp
