apiVersion: v1
kind: Pod
metadata:
  name: echo-screen
spec:
  containers:
  - image: quay.io/mangirdas/rpi-demo-app
    command:
      - ./demo
    imagePullPolicy: Always
    name: demo-app
    resources:
      requests:
        memory: 50Mi
        cpu: 100m
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
    volumeMounts:
    - mountPath: /dev
      name: dev
    - mountPath: /run
      name: run
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
    kubernetes.io/hostname: podman
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  volumes:
  - hostPath:
      path: /dev
      type: DirectoryOrCreate
    name: dev
  - hostPath:
      path: /run
      type: DirectoryOrCreate
    name: run
